server:
  port: 8099


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_batch
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always